import hashlib
import socket
import ssl
from urllib.parse import urljoin

from cryptography import x509
from cryptography.hazmat.primitives import hashes as crypto_hashes
from selectolax.parser import HTMLParser

from opendir.capture.fetcher import Fetcher


def _sha256(data: bytes) -> str:
    return hashlib.sha256(data).hexdigest()


def header_order_hash(headers: list[tuple[str, str]]) -> str:
    names = ",".join(k.lower() for k, _ in headers)
    return _sha256(names.encode())


def template_hash(html: str) -> str:
    # Structural template signature: the SET of distinct root-to-node tag paths.
    # Invariant to entry text/hrefs (file names, dates, sizes) and to entry COUNT,
    # so two directories generated by the same autoindex template collide even with
    # completely different contents; different templates (e.g. <table> vs <pre>) differ.
    tree = HTMLParser(html)
    paths = set()
    for node in tree.css("*"):
        parts = []
        cur = node
        while cur is not None and cur.tag not in (None, "-undef"):
            parts.append(cur.tag)
            cur = cur.parent
        if parts:
            paths.add("/".join(reversed(parts)))
    return _sha256("\n".join(sorted(paths)).encode())


def favicon_sha256(fetcher: Fetcher, base_url: str) -> str | None:
    root = urljoin(base_url, "/favicon.ico")
    r = fetcher.fetch(root)
    if r.status == 200 and r.body:
        return _sha256(r.body.encode("utf-8", "surrogatepass"))
    return None


def fetch_tls(host: str, port: int = 443) -> dict | None:
    try:
        ctx = ssl.create_default_context()
        ctx.check_hostname = False
        ctx.verify_mode = ssl.CERT_NONE
        with socket.create_connection((host, port), timeout=10) as sock:
            with ctx.wrap_socket(sock, server_hostname=host) as ssock:
                der = ssock.getpeercert(binary_form=True)
        if der is None:
            return None
        cert = x509.load_der_x509_certificate(der)
        fp = cert.fingerprint(crypto_hashes.SHA256()).hex()
        return {
            "sha256": fp,
            "issuer": cert.issuer.rfc4514_string(),
            "subject": cert.subject.rfc4514_string(),
            "not_before": cert.not_valid_before_utc.isoformat(),
            "not_after": cert.not_valid_after_utc.isoformat(),
            "self_signed": cert.issuer == cert.subject,
        }
    except (OSError, ssl.SSLError, ValueError):
        return None
