# Generated by Django 6.0.7 on 2026-07-21 19:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dedup_key', models.CharField(max_length=1024, unique=True)),
                ('url', models.TextField()),
                ('source', models.CharField(max_length=64)),
                ('source_meta', models.JSONField(blank=True, default=dict)),
                ('first_seen', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('pending', 'pending'), ('captured', 'captured'), ('error', 'error')], default='pending', max_length=16)),
                ('last_captured_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Snapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fetched_at', models.DateTimeField(auto_now_add=True)),
                ('http_status', models.IntegerField(blank=True, null=True)),
                ('headers', models.JSONField(blank=True, default=list)),
                ('server_banner', models.CharField(blank=True, default='', max_length=512)),
                ('server_kind', models.CharField(blank=True, default='unknown', max_length=32)),
                ('listing_entries', models.JSONField(blank=True, default=list)),
                ('entry_count', models.IntegerField(default=0)),
                ('raw_html_sha256', models.CharField(blank=True, default='', max_length=64)),
                ('header_order_sha256', models.CharField(blank=True, default='', max_length=64)),
                ('template_sha256', models.CharField(blank=True, default='', max_length=64)),
                ('favicon_sha256', models.CharField(blank=True, max_length=64, null=True)),
                ('tls', models.JSONField(blank=True, null=True)),
                ('error', models.TextField(blank=True, default='')),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='snapshots', to='opendir.candidate')),
            ],
            options={
                'indexes': [models.Index(fields=['candidate', 'fetched_at'], name='opendir_sna_candida_4a927b_idx')],
            },
        ),
    ]
