# Generated by Django 6.0.7 on 2026-07-21 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opendir', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='snapshot',
            name='final_url',
            field=models.TextField(blank=True, default=''),
        ),
    ]
