# Generated by Django 6.0.7 on 2026-07-22 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opendir', '0002_snapshot_final_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='snapshot',
            name='is_open_dir',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='snapshot',
            name='title',
            field=models.CharField(blank=True, default='', max_length=512),
        ),
    ]
