# Generated by Django 6.0.7 on 2026-07-22 15:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opendir', '0003_snapshot_is_open_dir_snapshot_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='Classification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=32)),
                ('confidence', models.FloatField()),
                ('reasons', models.JSONField(blank=True, default=list)),
                ('features', models.JSONField(blank=True, default=dict)),
                ('extractor_version', models.CharField(max_length=16)),
                ('ruleset_version', models.CharField(max_length=16)),
                ('classified_at', models.DateTimeField(auto_now_add=True)),
                ('snapshot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classifications', to='opendir.snapshot')),
            ],
        ),
    ]
