# Generated by Django 6.0.7 on 2026-07-22 15:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opendir', '0004_classification'),
    ]

    operations = [
        migrations.CreateModel(
            name='PayloadHash',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=512)),
                ('url', models.TextField()),
                ('sha256', models.CharField(blank=True, default='', max_length=64)),
                ('md5', models.CharField(blank=True, default='', max_length=32)),
                ('tlsh', models.CharField(blank=True, default='', max_length=70)),
                ('size', models.BigIntegerField(default=0)),
                ('error', models.TextField(blank=True, default='')),
                ('vt', models.JSONField(blank=True, null=True)),
                ('hashed_at', models.DateTimeField(auto_now_add=True)),
                ('snapshot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payload_hashes', to='opendir.snapshot')),
            ],
        ),
    ]
