# Generated by Django 6.0.7 on 2026-07-22 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opendir', '0005_payloadhash'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payloadhash',
            name='tlsh',
            field=models.CharField(blank=True, default='', max_length=80),
        ),
    ]
